workflows:
  windows-build:
    name: Linux Build
    instance_type: linux
    max_build_duration: 60
    environment:
      node: 16.13.1
    
    scripts: 
      - name: Installing packags
        script: yarn install
      - name: Installing RPM to build for arch linux
        script: sudo apt install rpm
      - name: Building Applications
        script: yarn run make

      