workflows:
  linux-build:
    name: Linux Build
    instance_type: linux
    environment:
      node: 16.14.0
    
    scripts: 
      - name: Installing packages
        script: yarn install
      - name: Installing RPM to build for arch linux
        script: sudo apt install rpm -y
      - name: Building Applications
        script: yarn run make

  windows-build:
    name: Windows Build
    instance_type: windows_x2
    
    scripts:
      - name: Installing Nodejs
        script:  choco install nodejs --version 16.14.0
      - name: Installing packages
        script: yarn install
      - name: Building Applications
        script: yarn run make

  macos-build:
    name: macOS Build
    instance_type: mac_mini
    environment:
      node: 16.14.0
    
    scripts:
      - name: Installing packages
        script: yarn install
      - name: Building Applications
        script: yarn run make

      